server:
  port: 8761
  
spring:  application:    name: REGISTRY-SERVER
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost        